export const styles = {
	header: 'py-8 lg:py-16 lg:h-full lg:flex lg:flex-col lg:justify-between lg:sticky lg:top-0 lg:max-h-dvh',
	topInfo: 'flex flex-col items-start lg:flex-none',
	imageWrap: 'hidden lg:block relative w-40 aspect-square mb-4 inline-block rounded-full overflow-hidden last:mb-0',
	image: 'absolute top-0 left-0 w-full h-full object-cover',
	heading: 'mb-1 lg:mb-2 font-bold tracking-tight text-slate-200 text-4xl md:text-5xl last:mb-0',
	headingLink: 'lg:hover:text-teal-300 transition-colors',
	position: 'mb-4 font-medium tracking-tight text-slate-200 text-xl last:mb-0',
	description: 'mb-4 md:max-w-lg lg:max-w-xs text-slate-400 last:mb-0',
	additionalList: 'mb-4 flex flex-col gap-1 last:mb-0',
	item: 'flex align-center gap-2 text-slate-400',
	additionalIcon: 'w-4',
	bottomList: 'flex gap-4 text-slate-400',
	bottomItem: 'w-8',
	bottomLink: 'lg:hover:text-teal-300 transition-colors',
};
