export const styles = {
	list: 'flex flex-col gap-10',
	clickableWrap: 'group isolate flex gap-4 lg:p-4 relative before:absolute before:top-0 before:left-0 before:right-0 before:-z-10 before:bottom-0 before:bg-white before:rounded-md before:opacity-0 before:transition-opacity hover:before:opacity-5',
	imageHolder: 'w-1/4',
	imageWrap: 'aspect-square relative border border-slate-800 rounded-md overflow-hidden transition-colors group-hover:border-teal-300',
	image: 'absolute top-0 left-0 w-full h-full object-cover',
	textContainer: 'w-3/4',
	link: 'mb-1',
	description: 'text-slate-400 mb-3',
	externalLinksWrap: 'flex gap-3 flex-wrap mb-3',
	additionalItemsWrap: 'flex gap-2 flex-wrap',
	additionalItem: 'bg-teal-900 border border-teal-800 text-teal-300 bg-opacity-20 px-2 py-1 rounded-full text-xs',
	nonClickableWrap: 'flex gap-4 lg:p-4',
	nonClickableImageWrap: 'border border-teal-300 rounded-md aspect-square flex justify-center items-center',
	nonClickableImageText: 'text-4xl font-bold text-teal-300',
	heading: 'font-bold text-slate-200 mb-1',
	locationWrap: 'flex align-center gap-2 text-slate-200 mb-3',
	locationIcon: 'w-4 text-slate-400',
	locationText: 'font-bold',
};
